const restaurants = [
  {
    name: "Spicy Treats",
    rating: 4.5,
    location: "Mumbai",
    country: "India",
    famousDish: "Butter Chicken",
    image: {
      filename: "listingimage",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjAMLedZRk2kc2Gg7NC0jRaHIjxa1-vf-b_A&s",
    },
  },
  {
    name: "Pasta Palace",
    rating: 4.7,
    location: "Rome",
    country: "Italy",
    famousDish: "Carbonara",
    image: {
      filename: "listingimage",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxqfyojxMBijikrAeZvgsCyIDMD-rCktUBPw&s",
    },
  },
  {
    name: "Sushi World",
    rating: 4.8,
    location: "Tokyo",
    country: "Japan",
    famousDish: "Sushi Platter",
    image: {
      filename: "listingimage",
      url: "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/chorizo-mozarella-gnocchi-bake-cropped-9ab73a3.jpg?resize=768,574",
    },
  },
  {
    name: "Tex-Mex Haven",
    rating: 4.6,
    location: "Dallas",
    country: "USA",
    famousDish: "Tacos",
    image: {
      filename: "listingimage",
      url: "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/easy-chocolate-molten-cakes-37a25eb.jpg",
    },
  },
  {
    name: "Parisian Delights",
    rating: 4.9,
    location: "Paris",
    country: "France",
    famousDish: "Croissants",
    image: {
      filename: "listingimage",
      url: "https://static.vecteezy.com/system/resources/previews/035/985/777/non_2x/ai-generated-tcookie-plate-dessert-food-photo.jpg",
    },
  },
  {
    name: "Middle East Feast",
    rating: 4.4,
    location: "Dubai",
    country: "UAE",
    famousDish: "Shawarma",
    image: {
      filename: "listingimage",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJ9aGuhB3Hu7eQhBYFOr-o0xtKFKx70lHBmA&s",
    },
  },
  {
    name: "BBQ King",
    rating: 4.5,
    location: "Austin",
    country: "USA",
    famousDish: "Smoked Brisket",
    image: {
      filename: "listingimage",
      url: "https://media.istockphoto.com/id/1081422898/photo/pan-fried-duck.jpg?s=612x612&w=0&k=20&c=kzlrX7KJivvufQx9mLd-gMiMHR6lC2cgX009k9XO6VA=",
    },
  },
  {
    name: "Thai Treats",
    rating: 4.6,
    location: "Bangkok",
    country: "Thailand",
    famousDish: "Pad Thai",
    image: {
      filename: "listingimage",
      url: "https://media.istockphoto.com/id/1081422898/photo/pan-fried-duck.jpg?s=612x612&w=0&k=20&c=kzlrX7KJivvufQx9mLd-gMiMHR6lC2cgX009k9XO6VA=",
    },
  },
  {
    name: "Shanghai Bites",
    rating: 4.7,
    location: "Shanghai",
    country: "China",
    famousDish: "Soup Dumplings",
    image: {
      filename: "listingimage",
      url: "https://media.istockphoto.com/id/1081422898/photo/pan-fried-duck.jpg?s=612x612&w=0&k=20&c=kzlrX7KJivvufQx9mLd-gMiMHR6lC2cgX009k9XO6VA=",
    },
  },
  {
    name: "Curry Corner",
    rating: 4.3,
    location: "Delhi",
    country: "India",
    famousDish: "Paneer Tikka",
    image: {
      filename: "listingimage",
      url: "https://sharethespice.com/wp-content/uploads/2024/02/Paneer-Tikka-Featured.jpg",
    },
  },
  {
    name: "Grill House",
    rating: 4.5,
    location: "Sydney",
    country: "Australia",
    famousDish: "Grilled Steaks",
    image: {
      filename: "listingimage",
      url: "https://images.ctfassets.net/3vz37y2qhojh/5GJTTAGHeDnQPlh47LlQvd/8e169c5fc1cde2bcdd70d129d800d606/Sliced-Chinese_Orange_Chicken.jpg?w=750&fit=fill&fm=webp",
    },
  },
  {
    name: "Pizza Paradise",
    rating: 4.8,
    location: "Naples",
    country: "Italy",
    famousDish: "Margherita Pizza",
    image: {
      filename: "listingimage",
      url: "https://static.vecteezy.com/system/resources/previews/015/933/115/non_2x/chole-bhature-is-a-north-indian-food-dish-a-combination-of-chana-masala-and-bhatura-or-puri-free-photo.jpg",
    },
  },
  {
    name: "German Bites",
    rating: 4.4,
    location: "Berlin",
    country: "Germany",
    famousDish: "Bratwurst",
    image: {
      filename: "listingimage",
      url: "https://static.vecteezy.com/system/resources/previews/015/933/115/non_2x/chole-bhature-is-a-north-indian-food-dish-a-combination-of-chana-masala-and-bhatura-or-puri-free-photo.jpg",
    },
  },
  {
    name: "Ocean's Catch",
    rating: 4.6,
    location: "Cape Town",
    country: "South Africa",
    famousDish: "Grilled Lobster",
    image: {
      filename: "listingimage",
      url: "https://www.foodiesfeed.com/wp-content/uploads/2023/06/pouring-honey-on-pancakes.jpg",
    },
  },
  {
    name: "Cafe de Madrid",
    rating: 4.5,
    location: "Madrid",
    country: "Spain",
    famousDish: "Paella",
    image: {
      filename: "listingimage",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvC1pGhW7_BRwnGuBguLE99tfA0faYflekCA&s",
    },
  },
  {
    name: "Nordic Bites",
    rating: 4.6,
    location: "Copenhagen",
    country: "Denmark",
    famousDish: "Smørrebrød",
    image: {
      filename: "listingimage",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiDW5SpduuUALUM2YJXI4Nhr_ytMw7qcQrlg&s",
    },
  },
  {
    name: "Pasta Palace",
    rating: 4.7,
    location: "Rome",
    country: "Italy",
    famousDish: "Carbonara",
    image: {
      filename: "listingimage",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxqfyojxMBijikrAeZvgsCyIDMD-rCktUBPw&s",
    },
  },
  {
    name: "Sushi World",
    rating: 4.8,
    location: "Tokyo",
    country: "Japan",
    famousDish: "Sushi Platter",
    image: {
      filename: "listingimage",
      url: "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/chorizo-mozarella-gnocchi-bake-cropped-9ab73a3.jpg?resize=768,574",
    },
  },
  {
    name: "Tex-Mex Haven",
    rating: 4.6,
    location: "Dallas",
    country: "USA",
    famousDish: "Tacos",
    image: {
      filename: "listingimage",
      url: "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/easy-chocolate-molten-cakes-37a25eb.jpg",
    },
  },
  {
    name: "Parisian Delights",
    rating: 4.9,
    location: "Paris",
    country: "France",
    famousDish: "Croissants",
    image: {
      filename: "listingimage",
      url: "https://static.vecteezy.com/system/resources/previews/035/985/777/non_2x/ai-generated-tcookie-plate-dessert-food-photo.jpg",
    },
  },
  {
    name: "Middle East Feast",
    rating: 4.4,
    location: "Dubai",
    country: "UAE",
    famousDish: "Shawarma",
    image: {
      filename: "listingimage",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJ9aGuhB3Hu7eQhBYFOr-o0xtKFKx70lHBmA&s",
    },
  },
  {
    name: "BBQ King",
    rating: 4.5,
    location: "Austin",
    country: "USA",
    famousDish: "Smoked Brisket",
    image: {
      filename: "listingimage",
      url: "https://media.istockphoto.com/id/1081422898/photo/pan-fried-duck.jpg?s=612x612&w=0&k=20&c=kzlrX7KJivvufQx9mLd-gMiMHR6lC2cgX009k9XO6VA=",
    },
  },
  {
    name: "Thai Treats",
    rating: 4.6,
    location: "Bangkok",
    country: "Thailand",
    famousDish: "Pad Thai",
    image: {
      filename: "listingimage",
      url: "https://media.istockphoto.com/id/1081422898/photo/pan-fried-duck.jpg?s=612x612&w=0&k=20&c=kzlrX7KJivvufQx9mLd-gMiMHR6lC2cgX009k9XO6VA=",
    },
  },
  {
    name: "Shanghai Bites",
    rating: 4.7,
    location: "Shanghai",
    country: "China",
    famousDish: "Soup Dumplings",
    image: {
      filename: "listingimage",
      url: "https://media.istockphoto.com/id/1081422898/photo/pan-fried-duck.jpg?s=612x612&w=0&k=20&c=kzlrX7KJivvufQx9mLd-gMiMHR6lC2cgX009k9XO6VA=",
    },
  },
  {
    name: "Curry Corner",
    rating: 4.3,
    location: "Delhi",
    country: "India",
    famousDish: "Paneer Tikka",
    image: {
      filename: "listingimage",
      url: "https://sharethespice.com/wp-content/uploads/2024/02/Paneer-Tikka-Featured.jpg",
    },
  },
  {
    name: "Grill House",
    rating: 4.5,
    location: "Sydney",
    country: "Australia",
    famousDish: "Grilled Steaks",
    image: {
      filename: "listingimage",
      url: "https://images.ctfassets.net/3vz37y2qhojh/5GJTTAGHeDnQPlh47LlQvd/8e169c5fc1cde2bcdd70d129d800d606/Sliced-Chinese_Orange_Chicken.jpg?w=750&fit=fill&fm=webp",
    },
  },
  {
    name: "Pizza Paradise",
    rating: 4.8,
    location: "Naples",
    country: "Italy",
    famousDish: "Margherita Pizza",
    image: {
      filename: "listingimage",
      url: "https://static.vecteezy.com/system/resources/previews/015/933/115/non_2x/chole-bhature-is-a-north-indian-food-dish-a-combination-of-chana-masala-and-bhatura-or-puri-free-photo.jpg",
    },
  },
  {
    name: "German Bites",
    rating: 4.4,
    location: "Berlin",
    country: "Germany",
    famousDish: "Bratwurst",
    image: {
      filename: "listingimage",
      url: "https://static.vecteezy.com/system/resources/previews/015/933/115/non_2x/chole-bhature-is-a-north-indian-food-dish-a-combination-of-chana-masala-and-bhatura-or-puri-free-photo.jpg",
    },
  },
  {
    name: "Ocean's Catch",
    rating: 4.6,
    location: "Cape Town",
    country: "South Africa",
    famousDish: "Grilled Lobster",
    image: {
      filename: "listingimage",
      url: "https://www.foodiesfeed.com/wp-content/uploads/2023/06/pouring-honey-on-pancakes.jpg",
    },
  },
  {
    name: "Cafe de Madrid",
    rating: 4.5,
    location: "Madrid",
    country: "Spain",
    famousDish: "Paella",
    image: {
      filename: "listingimage",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvC1pGhW7_BRwnGuBguLE99tfA0faYflekCA&s",
    },
  },
  {
    name: "Nordic Bites",
    rating: 4.6,
    location: "Copenhagen",
    country: "Denmark",
    famousDish: "Smørrebrød",
    image: {
      filename: "listingimage",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiDW5SpduuUALUM2YJXI4Nhr_ytMw7qcQrlg&s",
    },
  },
];

module.exports = { data: restaurants };
